dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - lts/*
  - node
install: npm ci
script:
  - npm link
  - npm run build:server:protos
  - npm run build:client
  - npm test
jobs:
  include:
    - stage: deploy
      if: type != pull_request && branch = master && commit_message !~ /no-deploy/
      node_js: lts/*
      install: npm ci
      script: skip
      deploy:
        provider: npm
        email: litichevskiydv@gmail.com
        api_key:
          secure: EFjk1m+JJTLAEiwEVSH2djEN5BjKmK5zNuEFjqVHIteFyBAi+YesT7ZAYiGUlNUIBpZZ0NYJ29qRjxARoKDQGGGXQvuFjgZs+XVYkK34QwA0TTHZU5X3TwA9tD5vK1Wdzl/hNWUL9n7EpGaxz+dGFZW1aru/ujPzaAxTDDeD3Ze2rLpVzbpj3sMIR9bzF2woFrdm7uwgSAT+0/qwR5dJrVp/kXq6d7NhzTH69WxsEuOf3h7hIgmVgMQS5/DGndVkdjbJJCl9mnNC4/OfjT5bNyykAHh1AAOcTPrLzQaYADNG2xlRUajRwQuJp+ivUR5ulPYCCpnFbZZi6wNPDMrMVAi90cg5n5RYTUoy1Vx3TJGQsuY81iGWfOvH2pMRCZ+mKsINXGa99LYc5+bT/syaQeR9q0o7xeOv5VZZDidDizly9OFbXn0u9HnPobL0Gk4OEP6296KXhAVJsptT//8820R9CW/bzEXP7IFHt/+CHtqO3f9eHt8pfjpociyiSxfCENMXfvx0NTC4cfx1HHESh8ve4b5e7zZgDHAd9WXOma1X9tBKpM7S5+nUN56jwxFpQ/fQ8745Mjwafeoq2K63T97nODZgv83hfJ7IY2a0AB6DCDKWchhyQasU9/1B6x41t41PYz2IF3ANiFwxadkrX6kwXBldRSmoWT87YeV39ms=
